# Generated by Django 3.1.7 on 2021-02-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="authuser", name="email_confirmed", field=models.BooleanField()
        )
    ]
